version: '3.8'

services:
  backend:
    build: ./backend # Carpeta donde se encuentra el Dockerfile del backend
    ports:
      - "3000:3000" # Mapeo de puerto del backend
    depends_on:
      - redis1
      - redis2
      - redis3

  redis1:
    image: bitnami/redis:7.0.10
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - ./redis1:/bitnami/redis/data

  redis2:
    image: bitnami/redis:7.0.10
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - ./redis2:/bitnami/redis/data

  redis3:
    image: bitnami/redis:7.0.10
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - ./redis3:/bitnami/redis/data
